<?php $this->inc('inc/header.php'); ?>

<h1>Exo\Response Object</h1>
<p>Instantiated by the View class, the Response object is what is sent back to the requesting user agent.</p>
<p>Using some magical double-calling, here is an example of what is generated by this very page-- minus the content, because that would look weird.</p>
<pre>
<?php var_dump($response); ?>
</pre>

<?php $this->inc('inc/footer.php'); ?>
